# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target '6-GettingCurrentDateAndTime' do
  pod 'RxSwift',    '~> 3.5.0'
  pod 'RxCocoa',    '~> 3.5.0'
  pod 'RxBlocking', '~> 3.5.0'
end

