# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TapCounter' do
  pod 'RxSwift',    '~> 2.0'
  pod 'RxCocoa',    '~> 2.0'
  pod 'RxBlocking', '~> 2.0'
#  pod 'RxTests',    '~> 2.0'
end

target 'TapCounterTests' do

end

target 'TapCounterUITests' do

end

